name: gamepads
resolution: workspace
description: A Flutter plugin to handle gamepad input across multiple platforms.
version: 0.1.8
homepage: https://github.com/flame-engine/gamepads
repository: https://github.com/flame-engine/gamepads/tree/main/packages/gamepads

flutter:
  plugin:
    platforms:
      windows:
        default_package: gamepads_windows

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  gamepads_platform_interface: ^0.1.2+1
  gamepads_windows: ^0.1.4

dev_dependencies:
  flame_lint: ^1.4.0
  flutter_test:
    sdk: flutter
